application:
  name: nairobi-devops
  namespace: nairobi-devops
  labels:
    app: nairobi-devops
    release: nairobi-devops-beta

imagePullPolicy: IfNotPresent

replicaCount: 1

image:
  repository: issachacha/demo-java
  tag: latest

service:
  name: web-service
  port: 80
  type: ClusterIP

config:
  key1: value1
  key2: value2
  key3: value3

secret:
  username: admin
  password: password