apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.service.name }}
  name: {{ .Values.application.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    service: {{ .Values.service.name }}